### ISSUE TITLE
Add /every command for recurring events and deadlines.

### ISSUE THREAD

**Issue by yzia2000** [AY1920S1-CS2113T-T09-1/main#139]
Have a command for recurring tasks in the format: 
/add <task description> /by <date time> /every <time interval>

When a task is completed or the deadline for the task is due, add the task back to the list with new <date time> which is equal to previous <date time> + <time interval>.

**Comment by ngjiewu** [comment]
Added this command in #168 [CS2113T-T09-1]-ngjiewu-Added RecurringDeadline and Event.
