### ISSUE TITLE
As a busy user, I want to be able to postpone or reschedule unimportant tasks so that I can focus on more pressing tasks.

### ISSUE THREAD

**Issue by EnriqueKhai** [AY1920S1-CS2113T-T09-1/main#90]

**Comment by ngjiewu** [comment]
Implemented in snooze feature, user can choose to postpone the task by typing the command **snooze INDEX NUMBER DURATION** (e.g. snooze 1 3 days) or by typing **snooze INDEX DATE TIME** (e.g. snooze 1 30/8/2018 1200)
